image: gilmrjc/all-py

before_script:
  - pip install coverage django-coverage-plugin
  - pip install tox

after_script:
  - coverage combine
  - coverage report --fail-under 80

testing:
  script:
    - coverage erase
    - tox --skip-missing
