image: gilmrjc/all-py:dockerfile

before_script:
  - pip install wheel
  - pip3 install wheel
  - pip install coverage django-coverage-plugin codacy-coverage codeclimate-test-reporter coveralls 
  - pip install tox

after_script:
  - coverage combine
  - coverage report
  - coverage xml

testing:
  script:
    - coverage erase
    - tox --skip-missing
