language: python

env:
  - TOXENV=py34-dj18
  - TOXENV=py34-dj19
  - TOXENV=py35-dj18
  - TOXENV=py35-dj19

install:
  - pip install tox
  
script:
  - tox
  
after_success:
  - pip install coverage codacy-coverage
  - covegare xml
  - python-codacy-coverage -r coverage.xml
