language: python

python:
  - "3.5"

install:
  - pip install coverage django-coverage-plugin codacy-coverage codeclimate-test-reporter  
  - pip install tox
  
script:
  - coverage erase
  - tox
  
after_success:
  - coverage combine
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - codeclimate-test-reporter
