language: python

python:
  - "3.5"

install:
  - pip install coverage django-coverage-plugin codacy-coverage codeclimate-test-reporter coveralls 
  - pip install tox
  
script:
  - coverage erase
  - tox --skip-missing
  
after_success:
  - coverage combine
  - coverage report
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - codeclimate-test-reporter
  - bash <(curl -s https://codecov.io/bash)
  - coveralls
