language: python

install:
  - export PYENV_ROOT="$HOME/.pyenv"
  - |
      if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
        pushd "$PYENV_ROOT" && git pull && popd
      else
        rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
      fi
      export PYPY_VERSION="4.0.1"
      "$PYENV_ROOT/bin/pyenv" install --skip-existing "pypy-$PYPY_VERSION"
      virtualenv --python="$PYENV_ROOT/versions/pypy-$PYPY_VERSION/bin/python" "$HOME/virtualenvs/pypy-$PYPY_VERSION"
      source "$HOME/virtualenvs/pypy-$PYPY_VERSION/bin/activate"
  - "$PYENV_ROOT/bin/pyenv" install -s 2.7.12
  - "$PYENV_ROOT/bin/pyenv" install -s 3.5.2
  - "$PYENV_ROOT/bin/pyenv" install -s 3.4.5
  - "$PYENV_ROOT/bin/pyenv" install -s 3.3.6
  - "$PYENV_ROOT/bin/pyenv" install -s pypy-4.0.1
  - "$PYENV_ROOT/bin/pyenv" rehash
  - "$PYENV_ROOT/bin/pyenv" local system 2.7.10 3.5.2 3.4.5 3.3.6 pypy-4.0.1
  - pip install coverage django-coverage-plugin codacy-coverage codeclimate-test-reporter coveralls 
  - pip install tox
  
script:
  - coverage erase
  - tox --skip-missing
  
after_success:
  - coverage combine
  - coverage report
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - codeclimate-test-reporter
  - bash <(curl -s https://codecov.io/bash)
  - coveralls
