version: '2'

services:
  app:
    restart: always
    build: .
    volumes:
      - .:/usr/src/app

  nginx:
    restart: always
    build: nginx
    links:
      - app:app
    ports:
      - "80:80"
