# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangopress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='commentmeta',
            name='comment',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.RemoveField(
            model_name='postmeta',
            name='post',
        ),
        migrations.DeleteModel(
            name='Term',
        ),
        migrations.DeleteModel(
            name='TermMeta',
        ),
        migrations.DeleteModel(
            name='TermRelationship',
        ),
        migrations.DeleteModel(
            name='TermTaxonomy',
        ),
        migrations.RemoveField(
            model_name='usermeta',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_date',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('PB', 'Public'), ('PV', 'Private'), ('T', 'Trash')], max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentMeta',
        ),
        migrations.DeleteModel(
            name='PostMeta',
        ),
        migrations.DeleteModel(
            name='UserMeta',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='djangopress.Category'),
            preserve_default=False,
        ),
    ]
