# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangopress.models


class Migration(migrations.Migration):

    dependencies = [
        ('djangopress', '0002_auto_20160714_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_status',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_filtered',
        ),
        migrations.RemoveField(
            model_name='post',
            name='guid',
        ),
        migrations.RemoveField(
            model_name='post',
            name='menu_order',
        ),
        migrations.RemoveField(
            model_name='post',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='post',
            name='password',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ping_status',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pinged',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_mime_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='to_ping',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, default=djangopress.models._get_default_category, on_delete=django.db.models.deletion.CASCADE, to='djangopress.Category'),
        ),
    ]
