# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20160726_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='separator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menus.Menu'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subitems', to='menus.MenuItem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='target',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
